# Site settings
title: Hyku
email:samvera-webcontact@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Digital Public Library of America, Stanford University, and DuraSpace,
  with funding from the Institute of Museum and Library Services,
  are working together to build a next-generation repository solution
baseurl: # the subpath of your site, e.g. /blog/
url: "http://hyku.samvera.org" # the base hostname & protocol for your site
twitter_username: HykuRepo
github_username:  hybox

# Build settings
markdown: kramdown
